[package]
name = "tatva-coloring"
version = "0.0.1"
edition = "2024"

[lib]
name = "_tatva_coloring"
crate-type = ["cdylib"]

[dependencies]
ahash = "0.8.12"
numpy = "0.27.1"
pyo3 = { version = "0.27.2", features = ["extension-module"] }
